sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 使用环境变量配置access-key-id和access-key-secret
    access-key-id: ${OSS_ACCESS_KEY_ID} #使用自己电脑环境变量中的id和secret
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: sky-out-projects
